### ISSUE TITLE
Redesign projects page

### ISSUE THREAD

**Issue by noahdavis319** [simutex/simutex#1]
The current projects page is a bare-minimum implementation to show users their account projects.

Redesign the page so that it shows the current projects, a button to create new projects, has a navigation bar with a link to logout, and more.

**Comment by dswilson4** [comment]
ME

**Comment by dswilson4** [comment]
Page shows table of user's current projects, button to make new project, logout, searching feature.  Could look into implementing some sort of pagination for the event that users have many projects

**Comment by dswilson4** [comment]
![image](https://user-images.githubusercontent.com/33137497/105010423-c73a5500-59df-11eb-9154-addffbbeb642.png)
