### ISSUE TITLE
Create account settings page

### ISSUE THREAD

**Issue by noahdavis319** [simutex/simutex#3]
User accounts currently cannot be modified.

Create a page where users can change their display name, but not their email address. Create a form to allow the user to change their account credentials. Password comparison can be perform client-side. If the user decides to bypass password comparison and ultimately don't know their password then they can reach out for help to their MongoDB administrator.

Requires creating a front-end page as well as exposing an API to first verify credentials (auth.js: auth.credentials) and then accept and apply the changes to the database. Additionally requires sending the new hashword (hashed password) back to the user so they can update their local cookie (cookie named "h")

**Comment by coryjk** [comment]
first
